//! Canonical tool representations — the internal lingua franca.
//!
//! All tools flowing through Coalesce are normalized to these types.
//! This is a superset that can express every provider's native capabilities
//! without information loss.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Canonical Tool Definition
// ---------------------------------------------------------------------------

/// A tool definition in Coalesce's canonical form.
/// Superset of all provider formats — fields that don't apply to a given
/// provider are dropped during egress translation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CanonicalTool {
    /// Unique name. For equivalence class members, this is the canonical
    /// name (e.g., "web_search"), not the provider-specific name.
    pub name: String,

    /// Human-readable description for the model.
    pub description: String,

    /// JSON Schema for the tool's input parameters.
    pub input_schema: serde_json::Value,

    /// Whether the client requires strict schema enforcement.
    /// Providers that can't enforce this get penalized in routing.
    #[serde(default)]
    pub strict: bool,

    /// Tool execution model.
    #[serde(default)]
    pub execution: ToolExecution,

    /// Equivalence class membership, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equivalence_class: Option<String>,

    /// Provider-specific metadata preserved through the round-trip
    /// (e.g., Anthropic's cache_control, OpenAI's strict additionalProperties).
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub provider_hints: HashMap<String, serde_json::Value>,

    /// Whether this tool can be deferred (loaded on demand via tool_search).
    #[serde(default)]
    pub defer_loading: bool,
}

/// How a tool gets executed.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type")]
pub enum ToolExecution {
    /// Client executes the tool and returns results (standard model).
    #[serde(rename = "client_side")]
    ClientSide,

    /// Provider executes the tool server-side (e.g., Anthropic web_search).
    /// If routing goes elsewhere, Rosetta must substitute or skip.
    #[serde(rename = "server_side")]
    ServerSide {
        /// Provider that offers this natively.
        native_provider: String,
    },

    /// Coalesce-managed tool (Universal Tool Plugin).
    /// Coalesce executes this itself, injecting results regardless of provider.
    #[serde(rename = "proxy_managed")]
    ProxyManaged {
        /// Reference to the handler (plugin name or WASM path).
        handler: String,
    },
}

impl Default for ToolExecution {
    fn default() -> Self {
        Self::ClientSide
    }
}

// ---------------------------------------------------------------------------
// Canonical Tool Call (model → client)
// ---------------------------------------------------------------------------

/// A tool invocation as returned by the model, normalized to canonical form.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CanonicalToolCall {
    /// Unique ID for this invocation. Generated by the model or by
    /// Rosetta if the provider doesn't produce one.
    pub id: String,

    /// Tool name (canonical, not provider-specific).
    pub name: String,

    /// Arguments as a JSON value.
    pub arguments: serde_json::Value,
}

// ---------------------------------------------------------------------------
// Canonical Tool Result (client → model)
// ---------------------------------------------------------------------------

/// A tool result being sent back to the model, normalized to canonical form.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CanonicalToolResult {
    /// The tool_call ID this result corresponds to.
    pub call_id: String,

    /// Result content.
    pub content: ToolResultContent,

    /// Whether this result represents an error.
    #[serde(default)]
    pub is_error: bool,
}

/// Content of a tool result.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ToolResultContent {
    /// Plain text result.
    #[serde(rename = "text")]
    Text { text: String },

    /// Structured JSON result.
    #[serde(rename = "json")]
    Json { data: serde_json::Value },

    /// Mixed content blocks (e.g., Anthropic-style multi-block results with images).
    #[serde(rename = "mixed")]
    Mixed { blocks: Vec<ContentBlock> },
}

/// A content block within a mixed tool result.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ContentBlock {
    #[serde(rename = "text")]
    Text { text: String },

    #[serde(rename = "image")]
    Image {
        media_type: String,
        data: String, // base64
    },

    #[serde(rename = "json")]
    Json { data: serde_json::Value },
}

// ---------------------------------------------------------------------------
// Tool Choice (how the model should use tools)
// ---------------------------------------------------------------------------

/// Normalized tool_choice across providers.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type")]
pub enum CanonicalToolChoice {
    /// Model decides whether to use tools.
    #[serde(rename = "auto")]
    Auto,

    /// Model must use at least one tool.
    #[serde(rename = "required")]
    Required,

    /// Model must not use tools.
    #[serde(rename = "none")]
    None,

    /// Model must use this specific tool.
    #[serde(rename = "specific")]
    Specific { name: String },
}

// ---------------------------------------------------------------------------
// Conversion helpers: OpenAI JSON ↔ Canonical
// ---------------------------------------------------------------------------

impl CanonicalTool {
    /// Parse an OpenAI-format tool definition into canonical form.
    pub fn from_openai(value: &serde_json::Value) -> Option<Self> {
        let func = value.get("function")?;
        let name = func.get("name")?.as_str()?.to_string();
        let description = func
            .get("description")
            .and_then(|d| d.as_str())
            .unwrap_or("")
            .to_string();
        let input_schema = func
            .get("parameters")
            .cloned()
            .unwrap_or(serde_json::json!({"type": "object"}));
        let strict = func
            .get("strict")
            .and_then(|s| s.as_bool())
            .unwrap_or(false);

        Some(Self {
            name,
            description,
            input_schema,
            strict,
            execution: ToolExecution::ClientSide,
            equivalence_class: None,
            provider_hints: HashMap::new(),
            defer_loading: false,
        })
    }

    /// Convert canonical tool to OpenAI format.
    pub fn to_openai(&self) -> serde_json::Value {
        let mut func = serde_json::json!({
            "name": self.name,
            "description": self.description,
            "parameters": self.input_schema,
        });
        if self.strict {
            func["strict"] = serde_json::json!(true);
        }
        serde_json::json!({
            "type": "function",
            "function": func,
        })
    }

    /// Parse an Anthropic-format tool definition into canonical form.
    pub fn from_anthropic(value: &serde_json::Value) -> Option<Self> {
        let name = value.get("name")?.as_str()?.to_string();
        let description = value
            .get("description")
            .and_then(|d| d.as_str())
            .unwrap_or("")
            .to_string();
        let input_schema = value
            .get("input_schema")
            .cloned()
            .unwrap_or(serde_json::json!({"type": "object"}));

        let mut provider_hints = HashMap::new();
        if let Some(cc) = value.get("cache_control") {
            provider_hints.insert("cache_control".to_string(), cc.clone());
        }

        // Detect server-side tools (Anthropic built-ins)
        let execution = match value.get("type").and_then(|t| t.as_str()) {
            Some("computer_20250124") | Some("text_editor_20250124") | Some("bash_20250124") => {
                ToolExecution::ServerSide {
                    native_provider: "anthropic".to_string(),
                }
            }
            _ => ToolExecution::ClientSide,
        };

        Some(Self {
            name,
            description,
            input_schema,
            strict: false,
            execution,
            equivalence_class: None,
            provider_hints,
            defer_loading: false,
        })
    }

    /// Convert canonical tool to Anthropic format.
    pub fn to_anthropic(&self) -> serde_json::Value {
        let mut tool = serde_json::json!({
            "name": self.name,
            "description": self.description,
            "input_schema": self.input_schema,
        });
        if let Some(cc) = self.provider_hints.get("cache_control") {
            tool["cache_control"] = cc.clone();
        }
        tool
    }
}

impl CanonicalToolCall {
    /// Parse an OpenAI-format tool call into canonical form.
    pub fn from_openai(value: &serde_json::Value) -> Option<Self> {
        let id = value.get("id")?.as_str()?.to_string();
        let func = value.get("function")?;
        let name = func.get("name")?.as_str()?.to_string();
        let args_str = func.get("arguments").and_then(|a| a.as_str()).unwrap_or("{}");
        let arguments: serde_json::Value =
            serde_json::from_str(args_str).unwrap_or(serde_json::json!({}));

        Some(Self {
            id,
            name,
            arguments,
        })
    }

    /// Convert canonical tool call to OpenAI format.
    pub fn to_openai(&self) -> serde_json::Value {
        serde_json::json!({
            "id": self.id,
            "type": "function",
            "function": {
                "name": self.name,
                "arguments": serde_json::to_string(&self.arguments).unwrap_or_default(),
            }
        })
    }

    /// Parse an Anthropic tool_use block into canonical form.
    pub fn from_anthropic(value: &serde_json::Value) -> Option<Self> {
        let id = value.get("id")?.as_str()?.to_string();
        let name = value.get("name")?.as_str()?.to_string();
        let arguments = value.get("input").cloned().unwrap_or(serde_json::json!({}));

        Some(Self {
            id,
            name,
            arguments,
        })
    }

    /// Convert canonical tool call to Anthropic tool_use block.
    pub fn to_anthropic(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "tool_use",
            "id": self.id,
            "name": self.name,
            "input": self.arguments,
        })
    }
}

impl CanonicalToolResult {
    /// Convert canonical tool result to OpenAI format (role: "tool" message).
    pub fn to_openai_message(&self) -> serde_json::Value {
        let content = match &self.content {
            ToolResultContent::Text { text } => text.clone(),
            ToolResultContent::Json { data } => serde_json::to_string(data).unwrap_or_default(),
            ToolResultContent::Mixed { blocks } => blocks
                .iter()
                .filter_map(|b| match b {
                    ContentBlock::Text { text } => Some(text.clone()),
                    ContentBlock::Json { data } => serde_json::to_string(data).ok(),
                    ContentBlock::Image { .. } => None,
                })
                .collect::<Vec<_>>()
                .join("\n"),
        };
        serde_json::json!({
            "role": "tool",
            "tool_call_id": self.call_id,
            "content": content,
        })
    }

    /// Convert canonical tool result to Anthropic tool_result block.
    pub fn to_anthropic_block(&self) -> serde_json::Value {
        let content = match &self.content {
            ToolResultContent::Text { text } => serde_json::json!(text),
            ToolResultContent::Json { data } => {
                serde_json::json!([{"type": "text", "text": serde_json::to_string(data).unwrap_or_default()}])
            }
            ToolResultContent::Mixed { blocks } => {
                let anthropic_blocks: Vec<serde_json::Value> = blocks
                    .iter()
                    .map(|b| match b {
                        ContentBlock::Text { text } => serde_json::json!({"type": "text", "text": text}),
                        ContentBlock::Image { media_type, data } => serde_json::json!({
                            "type": "image",
                            "source": {"type": "base64", "media_type": media_type, "data": data}
                        }),
                        ContentBlock::Json { data } => serde_json::json!({
                            "type": "text",
                            "text": serde_json::to_string(data).unwrap_or_default()
                        }),
                    })
                    .collect();
                serde_json::json!(anthropic_blocks)
            }
        };
        let mut block = serde_json::json!({
            "type": "tool_result",
            "tool_use_id": self.call_id,
            "content": content,
        });
        if self.is_error {
            block["is_error"] = serde_json::json!(true);
        }
        block
    }
}

impl CanonicalToolChoice {
    /// Parse from OpenAI format.
    pub fn from_openai(value: &serde_json::Value) -> Self {
        match value {
            serde_json::Value::String(s) => match s.as_str() {
                "auto" => Self::Auto,
                "required" => Self::Required,
                "none" => Self::None,
                _ => Self::Auto,
            },
            serde_json::Value::Object(obj) => {
                if let Some(func) = obj.get("function") {
                    if let Some(name) = func.get("name").and_then(|n| n.as_str()) {
                        return Self::Specific {
                            name: name.to_string(),
                        };
                    }
                }
                Self::Auto
            }
            _ => Self::Auto,
        }
    }

    /// Parse from Anthropic format.
    pub fn from_anthropic(value: &serde_json::Value) -> Self {
        match value.get("type").and_then(|t| t.as_str()) {
            Some("auto") => Self::Auto,
            Some("any") => Self::Required,
            Some("none") => Self::None,
            Some("tool") => {
                let name = value
                    .get("name")
                    .and_then(|n| n.as_str())
                    .unwrap_or("")
                    .to_string();
                Self::Specific { name }
            }
            _ => Self::Auto,
        }
    }

    /// Convert to OpenAI format.
    pub fn to_openai(&self) -> serde_json::Value {
        match self {
            Self::Auto => serde_json::json!("auto"),
            Self::Required => serde_json::json!("required"),
            Self::None => serde_json::json!("none"),
            Self::Specific { name } => serde_json::json!({
                "type": "function",
                "function": {"name": name}
            }),
        }
    }

    /// Convert to Anthropic format.
    pub fn to_anthropic(&self) -> serde_json::Value {
        match self {
            Self::Auto => serde_json::json!({"type": "auto"}),
            Self::Required => serde_json::json!({"type": "any"}),
            Self::None => serde_json::json!({"type": "none"}),
            Self::Specific { name } => serde_json::json!({"type": "tool", "name": name}),
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_openai_tool_roundtrip() {
        let openai_tool = serde_json::json!({
            "type": "function",
            "function": {
                "name": "get_weather",
                "description": "Get weather for a location",
                "strict": true,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {"type": "string"}
                    },
                    "required": ["location"],
                    "additionalProperties": false
                }
            }
        });

        let canonical = CanonicalTool::from_openai(&openai_tool).unwrap();
        assert_eq!(canonical.name, "get_weather");
        assert_eq!(canonical.strict, true);
        assert_eq!(canonical.execution, ToolExecution::ClientSide);

        let back = canonical.to_openai();
        assert_eq!(
            back["function"]["name"].as_str().unwrap(),
            "get_weather"
        );
        assert_eq!(back["function"]["strict"].as_bool().unwrap(), true);
    }

    #[test]
    fn test_anthropic_tool_roundtrip() {
        let anthropic_tool = serde_json::json!({
            "name": "get_weather",
            "description": "Get weather for a location",
            "input_schema": {
                "type": "object",
                "properties": {
                    "location": {"type": "string"}
                },
                "required": ["location"]
            },
            "cache_control": {"type": "ephemeral"}
        });

        let canonical = CanonicalTool::from_anthropic(&anthropic_tool).unwrap();
        assert_eq!(canonical.name, "get_weather");
        assert!(canonical.provider_hints.contains_key("cache_control"));

        let back = canonical.to_anthropic();
        assert_eq!(back["name"].as_str().unwrap(), "get_weather");
        assert!(back.get("cache_control").is_some());
    }

    #[test]
    fn test_openai_tool_call_roundtrip() {
        let openai_call = serde_json::json!({
            "id": "call_abc123",
            "type": "function",
            "function": {
                "name": "get_weather",
                "arguments": "{\"location\":\"Seattle\"}"
            }
        });

        let canonical = CanonicalToolCall::from_openai(&openai_call).unwrap();
        assert_eq!(canonical.id, "call_abc123");
        assert_eq!(canonical.name, "get_weather");
        assert_eq!(canonical.arguments["location"], "Seattle");

        let back = canonical.to_openai();
        assert_eq!(back["id"].as_str().unwrap(), "call_abc123");
    }

    #[test]
    fn test_anthropic_tool_call_roundtrip() {
        let anthropic_call = serde_json::json!({
            "type": "tool_use",
            "id": "toolu_01ABC",
            "name": "get_weather",
            "input": {"location": "Seattle"}
        });

        let canonical = CanonicalToolCall::from_anthropic(&anthropic_call).unwrap();
        assert_eq!(canonical.id, "toolu_01ABC");
        assert_eq!(canonical.name, "get_weather");

        let back = canonical.to_anthropic();
        assert_eq!(back["type"].as_str().unwrap(), "tool_use");
        assert_eq!(back["id"].as_str().unwrap(), "toolu_01ABC");
    }

    #[test]
    fn test_tool_result_to_openai() {
        let result = CanonicalToolResult {
            call_id: "call_abc123".into(),
            content: ToolResultContent::Text {
                text: "72°F, partly cloudy".into(),
            },
            is_error: false,
        };

        let msg = result.to_openai_message();
        assert_eq!(msg["role"].as_str().unwrap(), "tool");
        assert_eq!(msg["tool_call_id"].as_str().unwrap(), "call_abc123");
        assert_eq!(msg["content"].as_str().unwrap(), "72°F, partly cloudy");
    }

    #[test]
    fn test_tool_result_to_anthropic() {
        let result = CanonicalToolResult {
            call_id: "toolu_01ABC".into(),
            content: ToolResultContent::Text {
                text: "72°F, partly cloudy".into(),
            },
            is_error: true,
        };

        let block = result.to_anthropic_block();
        assert_eq!(block["type"].as_str().unwrap(), "tool_result");
        assert_eq!(block["tool_use_id"].as_str().unwrap(), "toolu_01ABC");
        assert_eq!(block["is_error"].as_bool().unwrap(), true);
    }

    #[test]
    fn test_tool_choice_conversions() {
        // OpenAI string forms
        assert_eq!(
            CanonicalToolChoice::from_openai(&serde_json::json!("auto")),
            CanonicalToolChoice::Auto
        );
        assert_eq!(
            CanonicalToolChoice::from_openai(&serde_json::json!("required")),
            CanonicalToolChoice::Required
        );

        // Anthropic object forms
        assert_eq!(
            CanonicalToolChoice::from_anthropic(&serde_json::json!({"type": "any"})),
            CanonicalToolChoice::Required
        );
        assert_eq!(
            CanonicalToolChoice::from_anthropic(&serde_json::json!({"type": "tool", "name": "get_weather"})),
            CanonicalToolChoice::Specific {
                name: "get_weather".into()
            }
        );

        // Round-trip
        let specific = CanonicalToolChoice::Specific {
            name: "search".into(),
        };
        let openai = specific.to_openai();
        assert_eq!(
            openai["function"]["name"].as_str().unwrap(),
            "search"
        );
        let anthropic = specific.to_anthropic();
        assert_eq!(anthropic["type"].as_str().unwrap(), "tool");
        assert_eq!(anthropic["name"].as_str().unwrap(), "search");
    }
}
